name: epub
version: 1.2.9
author: Colin Nelson <colinnlsn@gmail.com>
description: Epub Parser for Dart. Suitable for use on the Web or in Flutter 
homepage: https://github.com/orthros/dart-epub
environment:
  sdk: ">=2.0.0-dev.69.0 <3.0.0"
dependencies:
  async: "^2.0.8"
  archive: "^2.0.4"
  xml: "^3.2.0"
  image: "^2.0.4"
dev_dependencies:
  test: "^1.3.0"
  path: "^1.6.2"
